version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wordy
      POSTGRES_DB: wordy
      POSTGRES_PASSWORD: 123456